### ISSUE TITLE
Execution code fixes

### ISSUE THREAD

**Issue by OlivierArgentieri** [OlivierArgentieri-rezpackages/shellServer#2]
- [ ] empty spaces/tabs raise error
- [ ] need to test, but i think, when reached a maximum lens of rows and code, the executed code is truncated

**Comment by Lobeby** [comment]
Regarding the bug : when reached a maximum lens of rows and code, the executed code is truncated
I agree, and the threshold seems to be exactly 4096 characters
```
Traceback (most recent call last):
  File "C:\Users\Public\rez_packages_cache\commandServer\1.2.1\def5\a\libs\commandServer\__init__.py", line 123, in executeScript
    exec(script, self._globals, self._locals)
  File "<string>", line 142, in <module>
NameError: name 'prin' is not defined
```
